version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default-network
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default-network
    command: >
      sh -c "npx prisma migrate deploy && node dist/main.js"
  nextapp:
    build:
      context: ./next-app
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    container_name: nextapp
    ports:
      - 3000:3000
    env_file:
      - ./next-app/.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default-network
networks:
  default-network:
    driver: bridge
