version: '3.8'
services:
  postgres:
   image: postgres:latest
   restart: always
   env_file:
     - .env
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
   networks:
     - default-network  
   ports:
     - 5432
   volumes:
     - ./data:/var/lib/postgresql/data
  
  strapi:
    build:
      context: ./strapi
    volumes:
      - ./strapi/public/uploads:/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    restart: always
    networks:
      - default-network
  nextapp:
    build:
      context: ./next-app
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    ports:
      - 3000:3000
    env_file:
      - ./next-app/.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default-network
networks:
  default-network:
    driver: bridge